# 线上配置文件
server:
  port: ${PORT:10000}

spring:
  # Railway MySQL 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

mybatis-plus:
  configuration:
  # 生产环境关闭日志，避免日志刷屏
  # log-impl: ''

# 线上接口文档，基础认证防止别人乱访问
knife4j:
  basic:
    enable: true
    username: root
    password: 123456